// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDB6j1dqGKvatzelm2gWuVGg1po1IpPs',
    appId: '1:286554208893:web:4aa14d68c67fad602f0f14',
    messagingSenderId: '286554208893',
    projectId: 'y-sync-31c03',
    authDomain: 'y-sync-31c03.firebaseapp.com',
    storageBucket: 'y-sync-31c03.firebasestorage.app',
    measurementId: 'G-R9W2QECVHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm7PVXE5co_glMwu9KsCN_vxlkY-fd0g8',
    appId: '1:286554208893:android:e6cd7f5ae5af90c82f0f14',
    messagingSenderId: '286554208893',
    projectId: 'y-sync-31c03',
    storageBucket: 'y-sync-31c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXYX26bPZVoacjmYAfWi_BGyKprv7wFr0',
    appId: '1:286554208893:ios:a09eec899b6f88cc2f0f14',
    messagingSenderId: '286554208893',
    projectId: 'y-sync-31c03',
    storageBucket: 'y-sync-31c03.firebasestorage.app',
    iosBundleId: 'com.example.ySync',
  );
}
